name: Simple Cron Job

on:
  schedule:
    - cron: '0 6 * * *'    # 6:00 AM UTC (11:30 AM IST)
    - cron: '0 12 * * *'   # 12:00 PM UTC (5:30 PM IST)
    - cron: '0 18 * * *'   # 6:00 PM UTC (11:30 PM IST)
    - cron: '30 18 * * *'  # 6:30 PM UTC (12:00 AM IST)
    - cron: '0 0 * * *'    # 12:00 AM UTC (5:30 AM IST)
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message'
        required: false
        default: 'Manual test run'

jobs:
  test-job:
    name: Test Job
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Basic Info
      id: get-time
      shell: powershell
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        Write-Host "Run Time: $timestamp"
        Write-Host "Repository: ${{ github.repository }}"
        Write-Host "Run ID: ${{ github.run_id }}"
        echo "time=$timestamp" >> $env:GITHUB_OUTPUT
    
    - name: Create Report
      shell: powershell
      run: |
        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $reportContent = "Test Report - $timestamp`n"
        $reportContent += "Run ID: ${{ github.run_id }}`n"
        $reportContent += "Status: SUCCESS`n"
        $reportContent | Out-File -FilePath "test-report.txt" -Encoding UTF8
        Write-Host "Report created successfully"
    
    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ github.run_id }}
        path: test-report.txt
        retention-days: 7
